# Generated by Django 4.2.7 on 2023-11-13 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digestapi', '0003_alter_review_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='imageUrl',
            new_name='cover_image',
        ),
    ]
